//导航栏收缩
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
// 页面size
export const SET_SIZE = 'SET_SIZE'
export const SET_MENU = 'SET_MENU'
//tab 标签
export const ADD_TAB_VIEW = 'ADD_TAB_VIEW'
export const ADD_CACHE_TAB_VIEW = 'ADD_TAB_CACHE_VIEW'
export const UPDATE_TAB_VIEW = 'UPDATE_TAB_VIEW'
export const DEL_TAB_VIEW = 'DEL_TAB_VIEW'
export const DEL_CACHED_VIEW = 'DEL_CACHED_VIEW'
export const DEL_ALL_CACHED_VIEWS = 'DEL_ALL_CACHED_VIEWS'
export const DEL_ALL_TAB_VIEWS = 'DEL_ALL_TAB_VIEWS'
export const DEL_OTHERS_CACHED_VIEWS = 'DEL_OTHERS_CACHED_VIEWS'
export const DEL_OTHERS_TAB_VIEWS = 'DEL_OTHERS_TAB_VIEWS'
//user
export const SET_IDENTITY = 'SET_IDENTITY'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_HOME_ROUTE = 'SET_HOME_ROUTE'
export const SET_COUNT = 'SET_COUNT'